apiVersion: v1
kind: ConfigMap
metadata:
  name: inference-server-config
  namespace: cognibrew-baseline
data:
  LOG_LEVEL: "INFO"
  API_ENROLL_URL: "http://edge-gateway.cognibrew-baseline.svc:8000/api/v1/gateway/create_faces"
  MODEL_FRAMEWORK: "insightface"
  MODEL_NAME: "buffalo_sc"
