// This file is auto-generated by @hey-api/openapi-ts

export const BatchUploadSchema = {
    properties: {
        device_id: {
            type: 'string',
            title: 'Device Id',
            description: 'Unique edge device identifier'
        },
        date: {
            type: 'string',
            pattern: '^\\d{4}-\\d{2}-\\d{2}$',
            title: 'Date',
            description: 'ISO-8601 date string (YYYY-MM-DD)'
        },
        vectors: {
            items: {
                $ref: '#/components/schemas/VectorRecord'
            },
            type: 'array',
            minItems: 1,
            title: 'Vectors',
            description: 'Batch of face-embedding records'
        }
    },
    type: 'object',
    required: [
        'device_id',
        'date',
        'vectors'
    ],
    title: 'BatchUpload',
    description: 'Daily batch payload sent from an Edge device.'
} as const;

export const CreateFacesRequestSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        embedding: {
            items: {
                type: 'number'
            },
            type: 'array',
            maxItems: 512,
            minItems: 512,
            title: 'Embedding'
        },
        device_id: {
            type: 'string',
            title: 'Device Id',
            description: 'Source device or \'manual\'',
            default: 'manual'
        }
    },
    type: 'object',
    required: [
        'username',
        'embedding'
    ],
    title: 'CreateFacesRequest',
    description: 'Request to create (enroll) a baseline face vector.'
} as const;

export const DeleteFacesRequestSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username',
            description: 'Username whose faces to delete'
        },
        device_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Device Id',
            description: 'Specific device_id to delete. If omitted, deletes all faces for the user.'
        }
    },
    type: 'object',
    required: [
        'username'
    ],
    title: 'DeleteFacesRequest',
    description: 'Request to delete enrolled face records.'
} as const;

export const DeleteFacesResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status',
            default: 'ok'
        },
        deleted_count: {
            type: 'integer',
            title: 'Deleted Count',
            default: 0
        }
    },
    type: 'object',
    title: 'DeleteFacesResponse',
    description: 'Response for the delete_faces endpoint.'
} as const;

export const FaceRecordSchema = {
    properties: {
        s3_key: {
            type: 'string',
            title: 'S3 Key'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        embedding: {
            items: {
                type: 'number'
            },
            type: 'array',
            title: 'Embedding'
        },
        device_id: {
            type: 'string',
            title: 'Device Id'
        }
    },
    type: 'object',
    required: [
        's3_key',
        'username',
        'embedding',
        'device_id'
    ],
    title: 'FaceRecord',
    description: 'A single enrolled face record.'
} as const;

export const GetFacesRequestSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username',
            description: 'Username whose faces to retrieve'
        },
        device_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Device Id',
            description: 'Specific device_id to retrieve. If omitted, returns all faces for the user.'
        }
    },
    type: 'object',
    required: [
        'username'
    ],
    title: 'GetFacesRequest',
    description: 'Request to retrieve enrolled face records.'
} as const;

export const GetFacesResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status',
            default: 'ok'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        faces: {
            items: {
                $ref: '#/components/schemas/FaceRecord'
            },
            type: 'array',
            title: 'Faces'
        },
        count: {
            type: 'integer',
            title: 'Count',
            default: 0
        }
    },
    type: 'object',
    required: [
        'username'
    ],
    title: 'GetFacesResponse',
    description: 'Response for the get_faces endpoint.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const UploadResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status',
            default: 'ok'
        },
        s3_key: {
            type: 'string',
            title: 'S3 Key',
            description: 'Object key in S3'
        },
        record_count: {
            type: 'integer',
            title: 'Record Count',
            description: 'Number of records stored',
            default: 0
        }
    },
    type: 'object',
    required: [
        's3_key'
    ],
    title: 'UploadResponse',
    description: 'Standard success response after storing data.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;

export const VectorRecordSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username',
            description: 'The user identity label'
        },
        embedding: {
            items: {
                type: 'number'
            },
            type: 'array',
            maxItems: 512,
            minItems: 512,
            title: 'Embedding',
            description: '512-dim face embedding'
        },
        is_correct: {
            type: 'boolean',
            title: 'Is Correct',
            description: 'Edge feedback: was the recognition correct?',
            default: true
        }
    },
    type: 'object',
    required: [
        'username',
        'embedding'
    ],
    title: 'VectorRecord'
} as const;
