// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GatewayCreateFacesData, GatewayCreateFacesErrors, GatewayCreateFacesResponses, GatewayDeleteFacesData, GatewayDeleteFacesErrors, GatewayDeleteFacesResponses, GatewayGetFacesData, GatewayGetFacesErrors, GatewayGetFacesResponses, UtilsHealthCheckData, UtilsHealthCheckResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class GatewayService {
    /**
     * Create Faces
     *
     * Create (enroll) a baseline face-embedding vector.
     *
     * Stores under ``/enrollments/{username}/{device_id}.json``.
     */
    public static gatewayCreateFaces<ThrowOnError extends boolean = false>(options: Options<GatewayCreateFacesData, ThrowOnError>) {
        return (options.client ?? client).post<GatewayCreateFacesResponses, GatewayCreateFacesErrors, ThrowOnError>({
            url: '/api/v1/gateway/create_faces',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get Faces
     *
     * Retrieve enrolled face records for a given username.
     *
     * If ``device_id`` is provided, only that specific record is returned.
     * Otherwise **all** face records for the user are returned.
     */
    public static gatewayGetFaces<ThrowOnError extends boolean = false>(options: Options<GatewayGetFacesData, ThrowOnError>) {
        return (options.client ?? client).post<GatewayGetFacesResponses, GatewayGetFacesErrors, ThrowOnError>({
            url: '/api/v1/gateway/get_faces',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Faces
     *
     * Delete enrolled face records for a user.
     *
     * If ``device_id`` is provided, only that specific record is deleted.
     * Otherwise **all** face records for the user are removed.
     */
    public static gatewayDeleteFaces<ThrowOnError extends boolean = false>(options: Options<GatewayDeleteFacesData, ThrowOnError>) {
        return (options.client ?? client).post<GatewayDeleteFacesResponses, GatewayDeleteFacesErrors, ThrowOnError>({
            url: '/api/v1/gateway/delete_faces',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class UtilsService {
    /**
     * Health Check
     */
    public static utilsHealthCheck<ThrowOnError extends boolean = false>(options?: Options<UtilsHealthCheckData, ThrowOnError>) {
        return (options?.client ?? client).get<UtilsHealthCheckResponses, unknown, ThrowOnError>({ url: '/api/v1/utils/health-check/', ...options });
    }
}
