// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * BatchUpload
 *
 * Daily batch payload sent from an Edge device.
 */
export type BatchUpload = {
    /**
     * Device Id
     *
     * Unique edge device identifier
     */
    device_id: string;
    /**
     * Date
     *
     * ISO-8601 date string (YYYY-MM-DD)
     */
    date: string;
    /**
     * Vectors
     *
     * Batch of face-embedding records
     */
    vectors: Array<VectorRecord>;
};

/**
 * CreateFacesRequest
 *
 * Request to create (enroll) a baseline face vector.
 */
export type CreateFacesRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Embedding
     */
    embedding: [
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number
    ];
    /**
     * Device Id
     *
     * Source device or 'manual'
     */
    device_id?: string;
};

/**
 * DeleteFacesRequest
 *
 * Request to delete enrolled face records.
 */
export type DeleteFacesRequest = {
    /**
     * Username
     *
     * Username whose faces to delete
     */
    username: string;
    /**
     * Device Id
     *
     * Specific device_id to delete. If omitted, deletes all faces for the user.
     */
    device_id?: string | null;
};

/**
 * DeleteFacesResponse
 *
 * Response for the delete_faces endpoint.
 */
export type DeleteFacesResponse = {
    /**
     * Status
     */
    status?: string;
    /**
     * Deleted Count
     */
    deleted_count?: number;
};

/**
 * FaceRecord
 *
 * A single enrolled face record.
 */
export type FaceRecord = {
    /**
     * S3 Key
     */
    s3_key: string;
    /**
     * Username
     */
    username: string;
    /**
     * Embedding
     */
    embedding: Array<number>;
    /**
     * Device Id
     */
    device_id: string;
};

/**
 * GetFacesRequest
 *
 * Request to retrieve enrolled face records.
 */
export type GetFacesRequest = {
    /**
     * Username
     *
     * Username whose faces to retrieve
     */
    username: string;
    /**
     * Device Id
     *
     * Specific device_id to retrieve. If omitted, returns all faces for the user.
     */
    device_id?: string | null;
};

/**
 * GetFacesResponse
 *
 * Response for the get_faces endpoint.
 */
export type GetFacesResponse = {
    /**
     * Status
     */
    status?: string;
    /**
     * Username
     */
    username: string;
    /**
     * Faces
     */
    faces?: Array<FaceRecord>;
    /**
     * Count
     */
    count?: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * UploadResponse
 *
 * Standard success response after storing data.
 */
export type UploadResponse = {
    /**
     * Status
     */
    status?: string;
    /**
     * S3 Key
     *
     * Object key in S3
     */
    s3_key: string;
    /**
     * Record Count
     *
     * Number of records stored
     */
    record_count?: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VectorRecord
 */
export type VectorRecord = {
    /**
     * Username
     *
     * The user identity label
     */
    username: string;
    /**
     * Embedding
     *
     * 512-dim face embedding
     */
    embedding: [
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number
    ];
    /**
     * Is Correct
     *
     * Edge feedback: was the recognition correct?
     */
    is_correct?: boolean;
};

export type GatewayCreateFacesData = {
    body: CreateFacesRequest;
    path?: never;
    query?: never;
    url: '/api/v1/gateway/create_faces';
};

export type GatewayCreateFacesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GatewayCreateFacesError = GatewayCreateFacesErrors[keyof GatewayCreateFacesErrors];

export type GatewayCreateFacesResponses = {
    /**
     * Successful Response
     */
    200: UploadResponse;
};

export type GatewayCreateFacesResponse = GatewayCreateFacesResponses[keyof GatewayCreateFacesResponses];

export type GatewayGetFacesData = {
    body: GetFacesRequest;
    path?: never;
    query?: never;
    url: '/api/v1/gateway/get_faces';
};

export type GatewayGetFacesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GatewayGetFacesError = GatewayGetFacesErrors[keyof GatewayGetFacesErrors];

export type GatewayGetFacesResponses = {
    /**
     * Successful Response
     */
    200: GetFacesResponse;
};

export type GatewayGetFacesResponse = GatewayGetFacesResponses[keyof GatewayGetFacesResponses];

export type GatewayDeleteFacesData = {
    body: DeleteFacesRequest;
    path?: never;
    query?: never;
    url: '/api/v1/gateway/delete_faces';
};

export type GatewayDeleteFacesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GatewayDeleteFacesError = GatewayDeleteFacesErrors[keyof GatewayDeleteFacesErrors];

export type GatewayDeleteFacesResponses = {
    /**
     * Successful Response
     */
    200: DeleteFacesResponse;
};

export type GatewayDeleteFacesResponse = GatewayDeleteFacesResponses[keyof GatewayDeleteFacesResponses];

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type UtilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];
